// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggnnzccuxcyoleporcjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdnbm56Y2N1eGN5b2xlcG9yY2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2OTM0ODAsImV4cCI6MjA3NjI2OTQ4MH0.yPLrQtlAZxVNCzjDLHzx9VFlRNE6Hmg2hn1pTz9ICrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});